; Auto-generated. Do not edit!


(cl:in-package ur_msgs-msg)


;//! \htmlinclude FollowCartesianTrajectoryFeedback.msg.html

(cl:defclass <FollowCartesianTrajectoryFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass FollowCartesianTrajectoryFeedback (<FollowCartesianTrajectoryFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowCartesianTrajectoryFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowCartesianTrajectoryFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ur_msgs-msg:<FollowCartesianTrajectoryFeedback> is deprecated: use ur_msgs-msg:FollowCartesianTrajectoryFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowCartesianTrajectoryFeedback>) ostream)
  "Serializes a message object of type '<FollowCartesianTrajectoryFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowCartesianTrajectoryFeedback>) istream)
  "Deserializes a message object of type '<FollowCartesianTrajectoryFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowCartesianTrajectoryFeedback>)))
  "Returns string type for a message object of type '<FollowCartesianTrajectoryFeedback>"
  "ur_msgs/FollowCartesianTrajectoryFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowCartesianTrajectoryFeedback)))
  "Returns string type for a message object of type 'FollowCartesianTrajectoryFeedback"
  "ur_msgs/FollowCartesianTrajectoryFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowCartesianTrajectoryFeedback>)))
  "Returns md5sum for a message object of type '<FollowCartesianTrajectoryFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowCartesianTrajectoryFeedback)))
  "Returns md5sum for a message object of type 'FollowCartesianTrajectoryFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowCartesianTrajectoryFeedback>)))
  "Returns full string definition for message of type '<FollowCartesianTrajectoryFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowCartesianTrajectoryFeedback)))
  "Returns full string definition for message of type 'FollowCartesianTrajectoryFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowCartesianTrajectoryFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowCartesianTrajectoryFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowCartesianTrajectoryFeedback
))
