; Auto-generated. Do not edit!


(cl:in-package ur_msgs-msg)


;//! \htmlinclude FollowCartesianTrajectoryResult.msg.html

(cl:defclass <FollowCartesianTrajectoryResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:integer
    :initform 0))
)

(cl:defclass FollowCartesianTrajectoryResult (<FollowCartesianTrajectoryResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowCartesianTrajectoryResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowCartesianTrajectoryResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ur_msgs-msg:<FollowCartesianTrajectoryResult> is deprecated: use ur_msgs-msg:FollowCartesianTrajectoryResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <FollowCartesianTrajectoryResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ur_msgs-msg:success-val is deprecated.  Use ur_msgs-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowCartesianTrajectoryResult>) ostream)
  "Serializes a message object of type '<FollowCartesianTrajectoryResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'success)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'success)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'success)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'success)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowCartesianTrajectoryResult>) istream)
  "Deserializes a message object of type '<FollowCartesianTrajectoryResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'success)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'success)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'success)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'success)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowCartesianTrajectoryResult>)))
  "Returns string type for a message object of type '<FollowCartesianTrajectoryResult>"
  "ur_msgs/FollowCartesianTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowCartesianTrajectoryResult)))
  "Returns string type for a message object of type 'FollowCartesianTrajectoryResult"
  "ur_msgs/FollowCartesianTrajectoryResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowCartesianTrajectoryResult>)))
  "Returns md5sum for a message object of type '<FollowCartesianTrajectoryResult>"
  "952fc3b34491dbd8ce5170ced8b373fa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowCartesianTrajectoryResult)))
  "Returns md5sum for a message object of type 'FollowCartesianTrajectoryResult"
  "952fc3b34491dbd8ce5170ced8b373fa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowCartesianTrajectoryResult>)))
  "Returns full string definition for message of type '<FollowCartesianTrajectoryResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowCartesianTrajectoryResult)))
  "Returns full string definition for message of type 'FollowCartesianTrajectoryResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowCartesianTrajectoryResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowCartesianTrajectoryResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowCartesianTrajectoryResult
    (cl:cons ':success (success msg))
))
