// Generated by gencpp from file vision_based_picking/AcquireResponse.msg
// DO NOT EDIT!


#ifndef VISION_BASED_PICKING_MESSAGE_ACQUIRERESPONSE_H
#define VISION_BASED_PICKING_MESSAGE_ACQUIRERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_based_picking
{
template <class ContainerAllocator>
struct AcquireResponse_
{
  typedef AcquireResponse_<ContainerAllocator> Type;

  AcquireResponse_()
    : status(0)  {
    }
  AcquireResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int16_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::vision_based_picking::AcquireResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_based_picking::AcquireResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AcquireResponse_

typedef ::vision_based_picking::AcquireResponse_<std::allocator<void> > AcquireResponse;

typedef boost::shared_ptr< ::vision_based_picking::AcquireResponse > AcquireResponsePtr;
typedef boost::shared_ptr< ::vision_based_picking::AcquireResponse const> AcquireResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_based_picking::AcquireResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_based_picking::AcquireResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_based_picking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_based_picking::AcquireResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_based_picking::AcquireResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_based_picking::AcquireResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_based_picking::AcquireResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_based_picking::AcquireResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_based_picking::AcquireResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_based_picking::AcquireResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46fcc1fee3807f5925730339e5177777";
  }

  static const char* value(const ::vision_based_picking::AcquireResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46fcc1fee3807f59ULL;
  static const uint64_t static_value2 = 0x25730339e5177777ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_based_picking::AcquireResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_based_picking/AcquireResponse";
  }

  static const char* value(const ::vision_based_picking::AcquireResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_based_picking::AcquireResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 status\n"
"\n"
;
  }

  static const char* value(const ::vision_based_picking::AcquireResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_based_picking::AcquireResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AcquireResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_based_picking::AcquireResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_based_picking::AcquireResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_BASED_PICKING_MESSAGE_ACQUIRERESPONSE_H
