// Generated by gencpp from file vision_based_picking/AcquireRequest.msg
// DO NOT EDIT!


#ifndef VISION_BASED_PICKING_MESSAGE_ACQUIREREQUEST_H
#define VISION_BASED_PICKING_MESSAGE_ACQUIREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_based_picking
{
template <class ContainerAllocator>
struct AcquireRequest_
{
  typedef AcquireRequest_<ContainerAllocator> Type;

  AcquireRequest_()
    : the_request()
    , cam_index(0)  {
    }
  AcquireRequest_(const ContainerAllocator& _alloc)
    : the_request(_alloc)
    , cam_index(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _the_request_type;
  _the_request_type the_request;

   typedef int16_t _cam_index_type;
  _cam_index_type cam_index;





  typedef boost::shared_ptr< ::vision_based_picking::AcquireRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_based_picking::AcquireRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AcquireRequest_

typedef ::vision_based_picking::AcquireRequest_<std::allocator<void> > AcquireRequest;

typedef boost::shared_ptr< ::vision_based_picking::AcquireRequest > AcquireRequestPtr;
typedef boost::shared_ptr< ::vision_based_picking::AcquireRequest const> AcquireRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_based_picking::AcquireRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_based_picking::AcquireRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_based_picking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_based_picking::AcquireRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_based_picking::AcquireRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_based_picking::AcquireRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_based_picking::AcquireRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_based_picking::AcquireRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_based_picking::AcquireRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_based_picking::AcquireRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbd3bbe48e88ac081eadeeeb8701d7f3";
  }

  static const char* value(const ::vision_based_picking::AcquireRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbd3bbe48e88ac08ULL;
  static const uint64_t static_value2 = 0x1eadeeeb8701d7f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_based_picking::AcquireRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_based_picking/AcquireRequest";
  }

  static const char* value(const ::vision_based_picking::AcquireRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_based_picking::AcquireRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string the_request\n\
int16 cam_index\n\
";
  }

  static const char* value(const ::vision_based_picking::AcquireRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_based_picking::AcquireRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.the_request);
      stream.next(m.cam_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AcquireRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_based_picking::AcquireRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_based_picking::AcquireRequest_<ContainerAllocator>& v)
  {
    s << indent << "the_request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.the_request);
    s << indent << "cam_index: ";
    Printer<int16_t>::stream(s, indent + "  ", v.cam_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_BASED_PICKING_MESSAGE_ACQUIREREQUEST_H
