// Generated by gencpp from file ur_msgs/FollowCartesianTrajectoryFeedback.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_FOLLOWCARTESIANTRAJECTORYFEEDBACK_H
#define UR_MSGS_MESSAGE_FOLLOWCARTESIANTRAJECTORYFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur_msgs
{
template <class ContainerAllocator>
struct FollowCartesianTrajectoryFeedback_
{
  typedef FollowCartesianTrajectoryFeedback_<ContainerAllocator> Type;

  FollowCartesianTrajectoryFeedback_()
    {
    }
  FollowCartesianTrajectoryFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FollowCartesianTrajectoryFeedback_

typedef ::ur_msgs::FollowCartesianTrajectoryFeedback_<std::allocator<void> > FollowCartesianTrajectoryFeedback;

typedef boost::shared_ptr< ::ur_msgs::FollowCartesianTrajectoryFeedback > FollowCartesianTrajectoryFeedbackPtr;
typedef boost::shared_ptr< ::ur_msgs::FollowCartesianTrajectoryFeedback const> FollowCartesianTrajectoryFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ur_msgs': ['/home/bdml/catkin_ws/src/universal_robot/ur_msgs/msg', '/home/bdml/catkin_ws/devel/share/ur_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_msgs/FollowCartesianTrajectoryFeedback";
  }

  static const char* value(const ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
";
  }

  static const char* value(const ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowCartesianTrajectoryFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ur_msgs::FollowCartesianTrajectoryFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UR_MSGS_MESSAGE_FOLLOWCARTESIANTRAJECTORYFEEDBACK_H
