// Generated by gencpp from file ur_msgs/GripperMove.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_GRIPPERMOVE_H
#define UR_MSGS_MESSAGE_GRIPPERMOVE_H

#include <ros/service_traits.h>


#include <ur_msgs/GripperMoveRequest.h>
#include <ur_msgs/GripperMoveResponse.h>


namespace ur_msgs
{

struct GripperMove
{

typedef GripperMoveRequest Request;
typedef GripperMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperMove
} // namespace ur_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs::GripperMove > {
  static const char* value()
  {
    return "d1d55f75257890b063dd76689fbde353";
  }

  static const char* value(const ::ur_msgs::GripperMove&) { return value(); }
};

template<>
struct DataType< ::ur_msgs::GripperMove > {
  static const char* value()
  {
    return "ur_msgs/GripperMove";
  }

  static const char* value(const ::ur_msgs::GripperMove&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs::GripperMoveRequest> should match 
// service_traits::MD5Sum< ::ur_msgs::GripperMove > 
template<>
struct MD5Sum< ::ur_msgs::GripperMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::GripperMove >::value();
  }
  static const char* value(const ::ur_msgs::GripperMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::GripperMoveRequest> should match 
// service_traits::DataType< ::ur_msgs::GripperMove > 
template<>
struct DataType< ::ur_msgs::GripperMoveRequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::GripperMove >::value();
  }
  static const char* value(const ::ur_msgs::GripperMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs::GripperMoveResponse> should match 
// service_traits::MD5Sum< ::ur_msgs::GripperMove > 
template<>
struct MD5Sum< ::ur_msgs::GripperMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::GripperMove >::value();
  }
  static const char* value(const ::ur_msgs::GripperMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::GripperMoveResponse> should match 
// service_traits::DataType< ::ur_msgs::GripperMove > 
template<>
struct DataType< ::ur_msgs::GripperMoveResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::GripperMove >::value();
  }
  static const char* value(const ::ur_msgs::GripperMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_MESSAGE_GRIPPERMOVE_H
