// Generated by gencpp from file ur_msgs/GripperMoveResponse.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_GRIPPERMOVERESPONSE_H
#define UR_MSGS_MESSAGE_GRIPPERMOVERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur_msgs
{
template <class ContainerAllocator>
struct GripperMoveResponse_
{
  typedef GripperMoveResponse_<ContainerAllocator> Type;

  GripperMoveResponse_()
    : success(false)
    , has_object(false)  {
    }
  GripperMoveResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , has_object(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _has_object_type;
  _has_object_type has_object;





  typedef boost::shared_ptr< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GripperMoveResponse_

typedef ::ur_msgs::GripperMoveResponse_<std::allocator<void> > GripperMoveResponse;

typedef boost::shared_ptr< ::ur_msgs::GripperMoveResponse > GripperMoveResponsePtr;
typedef boost::shared_ptr< ::ur_msgs::GripperMoveResponse const> GripperMoveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_msgs::GripperMoveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ur_msgs': ['/home/bdml/catkin_ws/src/universal_robot/ur_msgs/msg', '/home/bdml/catkin_ws/devel/share/ur_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7c3e9566a7011a43c48ce986ef29228";
  }

  static const char* value(const ::ur_msgs::GripperMoveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7c3e9566a7011a4ULL;
  static const uint64_t static_value2 = 0x3c48ce986ef29228ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_msgs/GripperMoveResponse";
  }

  static const char* value(const ::ur_msgs::GripperMoveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
bool has_object\n\
\n\
";
  }

  static const char* value(const ::ur_msgs::GripperMoveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.has_object);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperMoveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_msgs::GripperMoveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_msgs::GripperMoveResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "has_object: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_object);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_MSGS_MESSAGE_GRIPPERMOVERESPONSE_H
